name: Generate ASCII Art

on:
  push:

jobs:
  generate_ascii_art:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Generate Dragon Art
        run: |
          cowsay -f dragon "Tarun Nayak" > dragon.txt
          cowsay -f dragon-and-cow "Tarun Nayak" > dragon-and-cow.txt
          cat dragon.txt
          cat dragon-and-cow.txt

      - name: Generate Elephant Art
        run: |
          cowsay -f elephant "Tarun Nayak" > elephant.txt
          cowsay -f elephant-in-suit "Tarun Nayak" > elephant-in-suit.txt
          cat elephant.txt
          cat elephant-in-suit.txt

      - name: Generate Ghost Art
        run: |
          cowsay -f ghostbusters "Tarun Nayak" > ghostbusters.txt
          cowsay -f ghost "Tarun Nayak" > ghost.txt
          cat ghostbusters.txt
          cat ghost.txt

      - name: List Files
        run: ls -la