name: schedule a backup now
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  backup:
   runs-on: ubuntu-latest
   steps:
     - name: Create expiry date
       run: |
        CURRENT_DATE = $(date + %y%m)
        if["$CURRENT_DATE " -gt "202703"]; then 
         echo "Backup period ended after March 2027"
         exit 0
         fi
     - name: Create Backup
       run: |
          mkdir backups
          echo "Backup taken on $(date)" > backups/backup-$(date +%Y%m%d).txt

     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
          name: daily-backup
          path: backups/
