name: secret varaible enviroment
on: 
  push:
    #workflow enviroment variable
env:
    COMPANY_NAME: TCS
    MY_NAME: TARUN NAYAK
    CITY: bhubaneswar
jobs:
  my_thirdjob:
    runs-on: ubuntu-latest
    env:
        USER_NAME: Tarun@123
        
    steps:
    - name: print user and password
      run: |
        echo "user name: $USER_NAME"
        echo "password: ${{secrets.password}}"
        echo "new password: ${{secrets.NEW_PASSWORD}}"

  my_firstjob:
    runs-on: ubuntu-latest
    #jobs level enviroment variable
    env:
        NAME: ludu
        CITY: CTC
    steps:
    - name: print job level variable
      run: |
        echo "my name is: $NAME" 
        echo "when company ill join: $COMPANY_NAME"
        echo "my name is $MY_NAME, i am from $CITY"
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: print step level variable    
      env:
        FIRST_STEPS: "getting a job"
        when: "when i am at my final year"
        
      run: |
        echo "my name is $MY_NAME, IM FROM CITY $CITY,"
        echo "i joined $COMPANY_NAME, $when ,my first wish is $FIRST_STEPS"

        
